/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.8 at Fri Jan 23 09:29:01 2026. */

#ifndef PB_MESHNETWORK_PB_H_INCLUDED
#define PB_MESHNETWORK_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MeshPacketType {
    MeshPacketType_RESERVED = 0,
    MeshPacketType_MESH_PACKET_TYPE_DREQ = 1,
    MeshPacketType_MESH_PACKET_TYPE_DREP = 2,
    MeshPacketType_MESH_PACKET_TYPE_TIMESYNC = 3
} MeshPacketType;
#define _MeshPacketType_MIN MeshPacketType_RESERVED
#define _MeshPacketType_MAX MeshPacketType_MESH_PACKET_TYPE_TIMESYNC
#define _MeshPacketType_ARRAYSIZE ((MeshPacketType)(MeshPacketType_MESH_PACKET_TYPE_TIMESYNC+1))

/* Struct definitions */
typedef struct _MeshNeighborInfo {
    uint32_t deviceID;
    uint8_t hopCount;
    int16_t rssi;
    uint16_t batVoltage;
/* @@protoc_insertion_point(struct:MeshNeighborInfo) */
} MeshNeighborInfo;

typedef struct _MeshPacketHeader {
    uint32_t senderID;
    uint32_t dReqID;
/* @@protoc_insertion_point(struct:MeshPacketHeader) */
} MeshPacketHeader;

typedef struct _TimeSyncMessage {
    uint32_t TimesyncID;
    uint32_t UtcTimestamp;
    uint8_t WakeUpInterval;
/* @@protoc_insertion_point(struct:TimeSyncMessage) */
} TimeSyncMessage;

typedef struct _MeshDRepPacket {
    MeshPacketHeader Header;
    uint32_t OGDreqSenderID;
    uint32_t ParentID;
    pb_size_t NeighborList_count;
    MeshNeighborInfo NeighborList[6];
/* @@protoc_insertion_point(struct:MeshDRepPacket) */
} MeshDRepPacket;

typedef struct _MeshDReqPacket {
    MeshPacketHeader Header;
    uint32_t OGDreqSenderID;
    uint8_t Ttl;
    int16_t Rssi;
/* @@protoc_insertion_point(struct:MeshDReqPacket) */
} MeshDReqPacket;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MeshPacketHeader_init_default            {0, 0}
#define MeshNeighborInfo_init_default            {0, 0, 0, 0}
#define MeshDReqPacket_init_default              {MeshPacketHeader_init_default, 0, 0, 0}
#define MeshDRepPacket_init_default              {MeshPacketHeader_init_default, 0, 0, 0, {MeshNeighborInfo_init_default, MeshNeighborInfo_init_default, MeshNeighborInfo_init_default, MeshNeighborInfo_init_default, MeshNeighborInfo_init_default, MeshNeighborInfo_init_default}}
#define TimeSyncMessage_init_default             {0, 0, 0}
#define MeshPacketHeader_init_zero               {0, 0}
#define MeshNeighborInfo_init_zero               {0, 0, 0, 0}
#define MeshDReqPacket_init_zero                 {MeshPacketHeader_init_zero, 0, 0, 0}
#define MeshDRepPacket_init_zero                 {MeshPacketHeader_init_zero, 0, 0, 0, {MeshNeighborInfo_init_zero, MeshNeighborInfo_init_zero, MeshNeighborInfo_init_zero, MeshNeighborInfo_init_zero, MeshNeighborInfo_init_zero, MeshNeighborInfo_init_zero}}
#define TimeSyncMessage_init_zero                {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MeshNeighborInfo_deviceID_tag            1
#define MeshNeighborInfo_hopCount_tag            2
#define MeshNeighborInfo_rssi_tag                3
#define MeshNeighborInfo_batVoltage_tag          4
#define MeshPacketHeader_senderID_tag            2
#define MeshPacketHeader_dReqID_tag              3
#define TimeSyncMessage_TimesyncID_tag           1
#define TimeSyncMessage_UtcTimestamp_tag         2
#define TimeSyncMessage_WakeUpInterval_tag       3
#define MeshDRepPacket_Header_tag                1
#define MeshDRepPacket_OGDreqSenderID_tag        2
#define MeshDRepPacket_ParentID_tag              3
#define MeshDRepPacket_NeighborList_tag          4
#define MeshDReqPacket_Header_tag                1
#define MeshDReqPacket_OGDreqSenderID_tag        2
#define MeshDReqPacket_Ttl_tag                   3
#define MeshDReqPacket_Rssi_tag                  4

/* Struct field encoding specification for nanopb */
extern const pb_field_t MeshPacketHeader_fields[3];
extern const pb_field_t MeshNeighborInfo_fields[5];
extern const pb_field_t MeshDReqPacket_fields[5];
extern const pb_field_t MeshDRepPacket_fields[5];
extern const pb_field_t TimeSyncMessage_fields[4];

/* Maximum encoded size of messages (where known) */
#define MeshPacketHeader_size                    12
#define MeshNeighborInfo_size                    29
#define MeshDReqPacket_size                      37
#define MeshDRepPacket_size                      212
#define TimeSyncMessage_size                     18

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESHNETWORK_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
