/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.8 at Tue Jul 15 15:49:52 2025. */

#include "meshNetwork.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MeshPacketHeader_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, MeshPacketHeader, packetType, packetType, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, MeshPacketHeader, senderID, packetType, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, MeshPacketHeader, dReqID, senderID, 0),
    PB_LAST_FIELD
};

const pb_field_t MeshNeighborInfo_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, MeshNeighborInfo, deviceID, deviceID, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, MeshNeighborInfo, hopCount, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, MeshNeighborInfo, rssi, hopCount, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, MeshNeighborInfo, snr, rssi, 0),
    PB_LAST_FIELD
};

const pb_field_t MeshDReqPacket_fields[6] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, MeshDReqPacket, Header, Header, &MeshPacketHeader_fields),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, MeshDReqPacket, OGDreqSenderID, Header, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, MeshDReqPacket, Ttl, OGDreqSenderID, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, MeshDReqPacket, Rssi, Ttl, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, MeshDReqPacket, Snr, Rssi, 0),
    PB_LAST_FIELD
};

const pb_field_t MeshDRepPacket_fields[6] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, MeshDRepPacket, Header, Header, &MeshPacketHeader_fields),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, MeshDRepPacket, OGDreqSenderID, Header, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, MeshDRepPacket, ParentID, OGDreqSenderID, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, MeshDRepPacket, NeighborCount, ParentID, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, MeshDRepPacket, NeighborList, NeighborCount, &MeshNeighborInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t TimeSyncMessage_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, TimeSyncMessage, SenderID, SenderID, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, TimeSyncMessage, UtcTimestamp, SenderID, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MeshDReqPacket, Header) < 65536 && pb_membersize(MeshDRepPacket, Header) < 65536 && pb_membersize(MeshDRepPacket, NeighborList[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MeshPacketHeader_MeshNeighborInfo_MeshDReqPacket_MeshDRepPacket_TimeSyncMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MeshDReqPacket, Header) < 256 && pb_membersize(MeshDRepPacket, Header) < 256 && pb_membersize(MeshDRepPacket, NeighborList[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MeshPacketHeader_MeshNeighborInfo_MeshDReqPacket_MeshDRepPacket_TimeSyncMessage)
#endif


/* @@protoc_insertion_point(eof) */
